services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: vector_backend
    stdin_open: true  # Разрешаем stdin
    tty: true         # Эмулируем терминал
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    working_dir: /app  # Явно указываем рабочую директорию
    command: python -m backend.main  # Используем модульный синтаксис

volumes:
  postgres_data: